// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// dotenv 默认读取 .env，这里改成读取 Next.js 惯用的 .env.local
import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
